import { type NextPage, type NextPageContext } from "next";
import Head from "next/head";
import { getSession } from "next-auth/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto max-w-7xl py-6"></main>
    </>
  );
};

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);
  if (!session?.user?.id) {
    return { redirect: { permanent: false, destination: "/auth/signin" } };
  } else {
    return { redirect: { permanent: false, destination: "/dashboard" } };
  }
}
export default Home;
